### ISSUE TITLE
PI output

### ISSUE THREAD

**Issue by aremazeilles** [STEPbySTEPproj/HF_metrics#5]
Right now the PI output is the following:

```yaml
total_errors:
  difference: 0.0
  exo: 16.0
  no exo: 16.0
total_execution_time:
  difference: 1.0
  exo: 1.0
  no exo: 0.0
total_responses_time:
  difference: 0.0
  exo: 68.747
  no exo: 68.747
```

We have to discuss on how to make it compatible with the [defined structure](https://eurobench.github.io/sofware_documentation/latest/pi_spec.html#_output_data)

In some protocol, we consider the use of exo or not as a change of condition, so that we would compute the metric independently with or without the exo.
If we want to stick to the current structure, a candidate might be, if maintained as is, to handle it as a matrix.

**Comment by aremazeilles** [comment]
Proposed structure: 

```yaml
type: vector
label: [error_exo, error_noexo, error_diff, ex_time_exo, ex_time_noexo, ex_time_diff, resp_time_exo, resp_time_noexo, resp_time_diff]
value: [16.0, 16.0, 0.0, 1.0, 0.0, 1.0, 68.747, 68.747, 0.0]
```


```

**Comment by aremazeilles** [comment]
Actually, no point to gather the three item together: Let's make 3 files:

file `pi_total_error.yaml`:

```yaml
type: vector
label: [error_exo, error_noexo, error_diff]
value: [16.0, 16.0, 0.0]
```

File `pi_execution_time`:
```yaml
type: vector
label: [ex_time_exo, ex_time_noexo, ex_time_diff]
value: [1.0, 0.0, 1.0]
```

File `pi_response_time.yaml`: 

```yaml
type: vector
label: [resp_time_exo, resp_time_noexo, resp_time_diff]
value: [68.747, 68.747, 0.0]
```
